{% set name = "azure-keyvault-certificates" %}
{% set version = "4.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 0c0154f3801b2384dd7fa4ed60366f4b0ae9111c5ffcca878d05368a004b87cf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - azure-common ~=1.1
    - azure-core >=1.7.0,<2.0.0
    - msrest >=0.6.21

test:
  imports:
    - azure.keyvault.certificates
    - azure.keyvault.certificates.aio

about:
  home: https://docs.microsoft.com/en-au/azure/key-vault/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Azure Key Vault Certificates client library for Python
  doc_url: https://azuresdkdocs.blob.core.windows.net/$web/python/azure-keyvault-certificates/latest/azure.keyvault.certificates.html
  dev_url: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/keyvault/azure-keyvault-certificates

extra:
  recipe-maintainers:
    - dhirschfeld
